# Data manupulation Govt And Tax codes

For the third year in a row, we found that service professionals valued three things above all others in their local government: a licensing system that is simple and makes compliance easy; a tax system that has clear rules and is easy to understand; and training and networking programs that help service professionals get their businesses up and running, comply with the local rules, and meet other professionals in their industries.

In [21]:
import pandas as pd

In [22]:
url = "https://taxfoundation.org/publications/state-business-tax-climate-index/"

In [23]:
scrape = pd.read_html(url)

In [25]:
df = scrape[1]
#df.to_csv("tax_data.csv")
df.head()

,Unnamed: 0_level_0,2016 Rank,2016 Score,2017 Rank,2017 Score,2018 Rank,2018 Score,2019 Rank,2019 Score,Change from 2018 to 2019,Unnamed: 10_level_0
,Rank,Score,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,Unnamed: 7_level_1,Unnamed: 8_level_1,Unnamed: 9_level_1,Unnamed: 10_level_1
0,Alabama,38,4.69,37,4.77,37.0,4.73,39.0,4.61,-2.0,-0.12
1,Alaska,2,7.34,3,7.25,3.0,7.15,2.0,7.35,1.0,0.20
2,Arizona,27,5.08,26,5.10,25.0,5.09,27.0,5.00,-2.0,-0.09
3,Arkansas,46,4.25,43,4.36,43.0,4.35,46.0,4.28,-3.0,-0.07
4,California,48,3.91,48,3.91,48.0,3.88,49.0,4.00,-1.0,0.12

In [16]:
df = pd.read_csv("tax_data_abbr.csv")
display(
    df.head(),

)

,state,Overall Rank,Corporate Tax Rank,Individual Income Tax Rank,Sales Tax Rank,Property Tax Rank,Unemployment Insurance Tax Rank
0,AL,39,20,30,48,15,12
1,AK,2,25,1,5,23,35
2,AZ,27,17,19,47,5,13
3,AR,46,40,40,44,26,34
4,CA,49,31,49,43,14,17

The Kauffman Foundation’s Index of Entrepreneurial Activity shows that entrepreneurship can be a safe harbor for cities during difficult economic periods – as individuals lose their jobs during economic downturns, entrepreneurship tends to rise as they turn towards self-employment to keep their skills up or help pay the bills, and it declines again as the labor market recovers. This suggests that cities that create the right environment for entrepreneurs will be better positioned to weather challenging economic periods. Listening directly to entrepreneurs as the Thumbtack survey does can help cities understand which policies are making them small business friendly and which are keeping small business at bay.

In [18]:
df_main = pd.read_csv("main.csv")

df_main.head()

,Id2,Geography,Travel time to work (min),Median Income,Percent bachelor's degree or higher,Establishments 2011,Establishments 2016,Pop: 2011,Pop: 2016,% Change,LAT,LON,city,state
0,10180,"Abilene, TX",1313825,48016,20.4,3844.0,3950.0,165858.0,170860.0,-0.250727,32.448736,-99.733144,Abilene,TX
1,10420,"Akron, OH",7359250,51598,31.0,16402.0,16390.0,701456.0,702221.0,-0.182022,41.081445,-81.519005,Akron,OH
2,10500,"Albany, GA",1215320,40667,18.6,3242.0,3123.0,161617.0,152506.0,2.084330,31.578507,-84.155741,Albany,GA
3,10580,"Albany-Schenectady-Troy, NY",9953675,65855,37.4,21027.0,21444.0,871478.0,881839.0,0.784933,42.763648,-73.653621,Albany-Schenectady-Troy,NY
4,10740,"Albuquerque, NM",9286780,50954,31.8,18466.0,18645.0,899149.0,913924.0,-0.662977,35.084386,-106.650422,Albuquerque,NM

In [19]:
df_main_wtaxrank = pd.merge(df_main, df, on = "state")

,Id2,Geography,Travel time to work (min),Median Income,Percent bachelor's degree or higher,Establishments 2011,Establishments 2016,Pop: 2011,Pop: 2016,% Change,LAT,LON,city,state,Overall Rank,Corporate Tax Rank,Individual Income Tax Rank,Sales Tax Rank,Property Tax Rank,Unemployment Insurance Tax Rank
0,10180,"Abilene, TX",1313825,48016,20.4,3844.0,3950.0,165858.0,170860.0,-0.250727,32.448736,-99.733144,Abilene,TX,15,49,6,37,37,18
1,11100,"Amarillo, TX",2334755,54478,23.7,6018.0,6348.0,254635.0,263491.0,1.938220,35.221997,-101.831297,Amarillo,TX,15,49,6,37,37,18
2,12420,"Austin-Round Rock, TX",26768530,71000,42.8,41924.0,50759.0,1783519.0,2056405.0,5.007286,30.508255,-97.678896,Austin-Round Rock,TX,15,49,6,37,37,18
3,13140,"Beaumont-Port Arthur, TX",3808355,49364,17.2,7845.0,7896.0,390535.0,409901.0,-4.105174,30.080174,-94.126556,Beaumont-Port Arthur,TX,15,49,6,37,37,18
4,15180,"Brownsville-Harlingen, TX",3125575,37061,17.0,6285.0,6376.0,414123.0,422135.0,-0.477560,26.190631,-97.696103,Brownsville-Harlingen,TX,15,49,6,37,37,18
5,17780,"College Station-Bryan, TX",2053660,42233,35.3,4316.0,4860.0,227997.0,254716.0,0.792389,30.825147,-96.492980,College Station-Bryan,TX,15,49,6,37,37,18
6,18580,"Corpus Christi, TX",3887750,53775,21.2,9257.0,9543.0,431381.0,452790.0,-1.784768,27.800583,-97.396381,Corpus Christi,TX,15,49,6,37,37,18
7,19100,"Dallas-Fort Worth-Arlington, TX",96061810,63812,33.9,141069.0,160269.0,6526566.0,7232599.0,2.519927,32.707875,-96.920913,Dallas-Fort Worth-Arlington,TX,15,49,6,37,37,18
8,21340,"El Paso, TX",8251840,42116,21.9,13494.0,14424.0,820790.0,842114.0,4.185235,31.761878,-106.485022,El Paso,TX,15,49,6,37,37,18
9,26420,"Houston-The Woodlands-Sugar Land, TX",90558810,61708,32.0,123784.0,139010.0,6086895.0,6772470.0,0.932319,30.174677,-95.453965,Houston-The Woodlands-Sugar Land,TX,15,49,6,37,37,18
10,28660,"Killeen-Temple, TX",3744975,52202,21.0,5907.0,6163.0,411595.0,435887.0,-1.480688,31.124151,-97.698227,Killeen-Temple,TX,15,49,6,37,37,18
11,29700,"Laredo, TX",2073050,35659,17.2,4779.0,5298.0,256496.0,271193.0,4.852079,27.503561,-99.507552,Laredo,TX,15,49,6,37,37,18
12,30980,"Longview, TX",2165935,45773,19.8,5337.0,5363.0,216666.0,217446.0,0.126708,32.500704,-94.740489,Longview,TX,15,49,6,37,37,18
13,31180,"Lubbock, TX",2473865,48671,30.2,6943.0,7304.0,290842.0,313910.0,-2.531211,33.577863,-101.855167,Lubbock,TX,15,49,6,37,37,18
14,32580,"McAllen-Edinburg-Mission, TX",6349950,36176,18.3,11206.0,11937.0,797810.0,849843.0,0.001232,26.215907,-98.325293,McAllen-Edinburg-Mission,TX,15,49,6,37,37,18
15,33260,"Midland, TX",1426960,65224,26.0,4655.0,5304.0,140308.0,168323.0,-5.022048,31.997346,-102.077915,Midland,TX,15,49,6,37,37,18
16,36220,"Odessa, TX",1579960,53254,15.4,3313.0,3584.0,140111.0,157462.0,-3.740626,31.845682,-102.367643,Odessa,TX,15,49,6,37,37,18
17,41660,"San Angelo, TX",1024595,49096,24.8,2636.0,2827.0,113614.0,120189.0,1.378890,31.463772,-100.437038,San Angelo,TX,15,49,6,37,37,18
18,41700,"San Antonio-New Braunfels, TX",28249580,56105,27.8,40516.0,44993.0,2196132.0,2429609.0,0.378440,29.703002,-98.124453,San Antonio-New Braunfels,TX,15,49,6,37,37,18
19,43300,"Sherman-Denison, TX",1295625,52095,19.4,2464.0,2526.0,121419.0,128235.0,-2.932752,33.755659,-96.536658,Sherman-Denison,TX,15,49,6,37,37,18
20,46340,"Tyler, TX",2114780,52572,24.9,5504.0,5775.0,213381.0,225290.0,-0.622654,32.351260,-95.301062,Tyler,TX,15,49,6,37,37,18
21,47020,"Victoria, TX",933730,55228,19.2,2819.0,2475.0,115873.0,100227.0,1.502712,28.805267,-97.003598,Victoria,TX,15,49,6,37,37,18
22,47380,"Waco, TX",2296065,46590,21.1,4938.0,5391.0,238564.0,264869.0,-1.668645,31.549333,-97.146670,Waco,TX,15,49,6,37,37,18
23,48660,"Wichita Falls, TX",1109135,44951,23.4,3469.0,3411.0,149024.0,150734.0,-2.787433,33.913709,-98.493387,Wichita Falls,TX,15,49,6,37,37,18
24,10420,"Akron, OH",7359250,51598,31.0,16402.0,16390.0,701456.0,702221.0,-0.182022,41.081445,-81.519005,Akron,OH,42,46,44,28,13,6
25,15940,"Canton-Massillon, OH",4020090,50811,23.4,8801.0,8648.0,405693.0,401281.0,-0.658074,40.796724,-81.521509,Canton-Massillon,OH,42,46,44,28,13,6
26,17460,"Cleveland-Elyria, OH",22823600,52131,30.3,51600.0,51247.0,2068283.0,2055612.0,-0.071915,41.391297,-82.112958,Cleveland-Elyria,OH,42,46,44,28,13,6
27,18140,"Columbus, OH",23198545,60294,36.0,38781.0,42106.0,1858464.0,2041520.0,-1.161648,39.961176,-82.998794,Columbus,OH,42,46,44,28,13,6
28,19380,"Dayton, OH",7686735,51427,27.4,17241.0,16528.0,845388.0,800683.0,1.216968,39.758948,-84.191607,Dayton,OH,42,46,44,28,13,6
29,30620,"Lima, OH",835445,47592,16.6,2516.0,2412.0,106094.0,103742.0,-1.960097,40.742551,-84.105226,Lima,OH,42,46,44,28,13,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,20100,"Dover, DE",2008270,54140,22.6,3177.0,3422.0,164834.0,174827.0,1.554947,39.158168,-75.524368,Dover,DE,11,50,41,2,9,3
273,22380,"Flagstaff, AZ",975490,55091,35.4,3529.0,3650.0,134511.0,140908.0,-1.266767,35.198284,-111.651302,Flagstaff,AZ,27,17,19,47,5,13
274,29420,"Lake Havasu City-Kingman, AZ",1434415,42423,11.3,3600.0,3697.0,202351.0,205249.0,1.244457,34.483901,-114.322455,Lake Havasu City-Kingman,AZ,27,17,19,47,5,13
275,38060,"Phoenix-Mesa-Scottsdale, AZ",52062550,58075,30.8,86667.0,94758.0,4263236.0,4661537.0,-0.006364,33.415184,-111.831472,Phoenix-Mesa-Scottsdale,AZ,27,17,19,47,5,13
276,39140,"Prescott, AZ",1788265,50420,24.0,5495.0,5825.0,211888.0,225562.0,-0.420794,34.540024,-112.468502,Prescott,AZ,27,17,19,47,5,13
277,46060,"Tucson, AZ",9952415,47560,31.9,20059.0,20180.0,989569.0,1016206.0,-2.033812,32.222607,-110.974711,Tucson,AZ,27,17,19,47,5,13
278,49740,"Yuma, AZ",1520700,43518,15.4,2897.0,2963.0,200870.0,205631.0,-0.089841,32.692651,-114.627692,Yuma,AZ,27,17,19,47,5,13
279,25060,"Gulfport-Biloxi-Pascagoula, MS",3876770,46434,21.7,5137.0,7175.0,250611.0,391266.0,-10.537638,30.413114,-89.072778,Gulfport-Biloxi-Pascagoula,MS,31,15,27,35,36,5
280,25620,"Hattiesburg, MS",1767070,46765,29.0,3305.0,3342.0,146509.0,148803.0,-0.439379,31.327119,-89.290339,Hattiesburg,MS,31,15,27,35,36,5
281,27140,"Jackson, MS",6313875,50632,29.9,12524.0,13146.0,545394.0,580178.0,-1.326696,32.298757,-90.184810,Jackson,MS,31,15,27,35,36,5
282,26300,"Hot Springs, AR",830565,42826,18.3,2663.0,2712.0,97124.0,97477.0,1.471230,34.503700,-93.055180,Hot Springs,AR,46,40,40,44,26,34
283,27860,"Jonesboro, AR",923275,41717,21.4,2760.0,2841.0,121569.0,129858.0,-3.635674,35.842297,-90.704279,Jonesboro,AR,46,40,40,44,26,34
284,30780,"Little Rock-North Little Rock-Conway, AR",7375465,51501,30.7,17486.0,17904.0,708084.0,734381.0,-1.275954,35.088696,-92.442101,Little Rock-North Little Rock-Conway,AR,46,40,40,44,26,34
285,38220,"Pine Bluff, AR",649990,37076,16.7,1642.0,1566.0,99334.0,94071.0,0.707257,34.228431,-92.003196,Pine Bluff,AR,46,40,40,44,26,34
286,29940,"Lawrence, KS",1365145,56345,52.0,2601.0,2713.0,112211.0,119440.0,-2.006994,38.971669,-95.235250,Lawrence,KS,28,34,21,31,20,15
287,45820,"Topeka, KS",2199490,56548,28.2,5314.0,5157.0,234380.0,233068.0,-2.408165,39.047345,-95.675158,Topeka,KS,28,34,21,31,20,15
288,48620,"Wichita, KS",6031980,53663,30.7,14404.0,14955.0,625039.0,645447.0,0.542536,37.687176,-97.330053,Wichita,KS,28,34,21,31,20,15
289,30020,"Lawton, OK",803520,50980,20.4,2194.0,2273.0,125815.0,127762.0,2.021929,34.603567,-98.395929,Lawton,OK,26,9,33,39,19,1
290,36420,"Oklahoma City, OK",13937780,55065,29.8,33111.0,35526.0,1278053.0,1373211.0,-0.141370,35.467560,-97.516428,Oklahoma City,OK,26,9,33,39,19,1
291,46140,"Tulsa, OK",9441415,51623,27.2,23852.0,24403.0,947382.0,987958.0,-1.891855,36.153982,-95.992775,Tulsa,OK,26,9,33,39,19,1
292,30700,"Lincoln, NE",3320505,59344,39.8,8208.0,8890.0,307165.0,326591.0,1.866628,40.813616,-96.702596,Lincoln,NE,24,28,26,9,40,9
293,31700,"Manchester-Nashua, NH",5638615,76254,37.3,10635.0,10944.0,401696.0,407761.0,1.374894,42.765366,-71.467566,Manchester-Nashua,NH,6,45,9,1,44,44
294,36260,"Ogden-Clearfield, UT",6646710,70227,30.4,11273.0,13665.0,555437.0,656061.0,2.626783,41.110777,-112.026054,Ogden-Clearfield,UT,8,5,10,16,3,16
295,39340,"Provo-Orem, UT",5353710,69288,38.2,10907.0,13056.0,541710.0,602543.0,7.617683,40.296898,-111.694648,Provo-Orem,UT,8,5,10,16,3,16
296,41100,"St. George, UT",984155,55056,28.3,3844.0,4795.0,141666.0,160245.0,10.277364,37.096528,-113.568416,St. George,UT,8,5,10,16,3,16
297,41620,"Salt Lake City, UT",12744160,68196,33.0,31390.0,32433.0,1145905.0,1186187.0,-0.186046,40.760779,-111.891047,Salt Lake City,UT,8,5,10,16,3,16
298,39660,"Rapid City, SD",1145225,51097,29.5,4251.0,4756.0,128361.0,143367.0,0.169299,44.080543,-103.231015,Rapid City,SD,3,1,1,33,28,39
299,43620,"Sioux Falls, SD",2440165,63931,34.1,6921.0,7645.0,232347.0,256479.0,0.067695,43.547303,-96.728333,Sioux Falls,SD,3,1,1,33,28,39
300,40340,"Rochester, MN",2157455,70078,36.7,4376.0,5141.0,187612.0,215884.0,2.096404,44.012122,-92.480199,Rochester,MN,43,42,46,27,31,25
301,41060,"St. Cloud, MN",1973610,56620,25.1,5164.0,5328.0,190014.0,195644.0,0.206767,45.557945,-94.163240,St. Cloud,MN,43,42,46,27,31,25